<!-- GROUP INSTRUCTIONS
=================================================== -->
<!-- 1. Add login CSS through this config rather than the Admin Style app, so it can be available before the admin is loaded. -->
<link rel="stylesheet" href="/perch/addons/apps/jaygeorge_perch_admin_style/variables.css">
<link rel="stylesheet" href="/perch/addons/apps/jaygeorge_perch_admin_style/login.css">
<!-- 2. Uncomment this out and add an extra stylesheet if you'd like to add extra branding for the login css. -->
<!-- <link rel="stylesheet" href="/perch/addons/plugins/ui/custom-login.css"> -->